--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WavyCraftNetwork/Quest
build-by-default: true
branches:
- main
projects:
  Quest:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...
